name: repo_viewer
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  oauth2: ^2.0.1
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  dio: ^5.0.0
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  riverpod: ^2.2.0
  freezed_annotation: ^2.2.0
  freezed: ^2.3.2
  webview_flutter: ^4.0.4
  flash: ^2.0.5+1
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lint: ^2.0.1


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
